FROM node:19.0.0-bullseye

ENV APP_FOLDER=/demo

ARG SERVICE_URL
ENV REACT_APP_SERVICE_URL $SERVICE_URL

ARG POLLING_TIME
ENV REACT_APP_POLLING_TIME $POLLING_TIME

COPY . ${APP_FOLDER}
WORKDIR ${APP_FOLDER}

RUN npm install

EXPOSE 3000
CMD ["npm", "start"]
